config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  mount Resque::Server, :at => "/resque"

  get 'requests',          to: 'requests#index',      as: :requests
  get 'requests/new',      to: 'requests#new',        as: :new_request
  post 'requests',         to: 'requests#create'
  get 'request/:id',       to: 'requests#show',       as: :request
  patch 'request/:id',     to: 'requests#update'
  delete 'request/:id',    to: 'requests#destroy'
  get 'request/:id/edit',  to: 'requests#edit',       as: :edit_request

  get 'users',          to: 'users#index',      as: :users
  get 'users/new',      to: 'users#new',        as: :new_user
  post 'users',         to: 'users#create'
  get 'user/:id',       to: 'users#show',       as: :user
  patch 'user/:id',     to: 'users#update'
  delete 'user/:id',    to: 'users#destroy'
  get 'user/:id/edit',  to: 'users#edit',       as: :edit_user

  get "/login",  to: "sessions#create",    as: :login
  post "/login", to: "sessions#create"
  delete "/logout",      to: "sessions#destroy",            as: :logout

  root "home#show"

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user

  validates :website, :stringmatch, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :requests

  validates :name, :email, presence: true
  validates :username, :password, :password_confirmation, presence: true, on: :create
  validates :username, :email, uniqueness: { case_sensitive: false }, on: :create
  validates :password, length: { minimum: 10, maximun: 20 }, on: :create
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :logged_in
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:current_user])
  end

  def logged_in
    if current_user == nil
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :logged_in, only: [:show]
  
  def show
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    @request = Request.all
  end

  def show
    @request = Request.find(params[:id])
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(params.require(:request).permit(:website, :stringmatch))
    @request.user_id = session[:current_user]
    if @request.save
      flash[:notice] = 'The request is successfully saved!'
      redirect_to user_path(session[:current_user])
    else
      render :new
    end
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(params.require(:request).permit(:website, :stringmatch))
      redirect_to user_path(session[:current_user])
    else
      render :edit
    end
  end

  def destroy
    Request.find(params[:id]).destroy
    redirect_to user_path(session[:current_user])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create
  skip_before_filter :logged_in, only: [:create, :new, :user]

  def new

  end

  def create
    if user && user.authenticate(params[:user][:password])
      session[:current_user] = user.id
      redirect_to user_path(user.id)
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to root_path
  end

  private
  def user
      User.find_by(username: params[:user][:username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :logged_in, only: [:new, :create]
  def index
  end

  def new
    @user = User.new
  end

  def show
    if current_user
      @user = User.find(session[:current_user])
    else
      redirect_to root_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'The User is successfully saved!'
      session[:current_user] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(session[:current_user])
  end

  def update
    @user = User.find(session[:current_user])
    if @user.update(params.require(:user).permit(:name, :email))
      redirect_to user_path(session[:current_user])
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/home/show.html.erb
<div class="sign-up">
  <%= form_tag login_path do %>
    <div class="form-field">
      <%= label_tag "user[username]", "Username" %>
      <%= text_field_tag "user[username]", "", class: 'form-control' %>
    </div>

    <div class="form_field">
      <%= label_tag "user[password]", "Password" %>
      <%= password_field_tag "user[password]", "", class: 'form-control' %>
    </div>

    <div class="form_field">
      <%= submit_tag "Sign in", class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WootWatcher</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
  <header class="nav-bar navbar-fixed-top">
    <span class="brand-header">
      <h1>Woot Watcher</h1>
    </span>

    <span class="signin-header">
      <% if session[:current_user] == nil %>
        <%= link_to "Sign Up", new_user_path%> |
        <%= link_to "Sign in", root_path %>
      <% else %>
        <%= link_to "#{current_user.name}", user_path(current_user.id) %> |
        <%= link_to "Sign out", logout_path, :method => "delete"  %>
      <% end %>
    </span>

  </header>
  <div class="container">
    <%= yield %>
  </div>
</html>

app/views/requests/create.html.erb
<h1>Views#create</h1>
<p>Find me in app/views/views/create.html.erb</p>

app/views/requests/destroy.html.erb
<h1>Views#destroy</h1>
<p>Find me in app/views/views/destroy.html.erb</p>

app/views/requests/edit.html.erb
<h1>Edit Request</h1>

<div class="sign-up">

  <%= form_for @request do |f| %>
  <div class="form-field">
    <%= f.label :website%>
    <%= f.text_field :website, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @request, col: :website %>
  </div>

  <div class='form-field'>
    <%= f.label :stringmatch %>
    <%= f.text_field :stringmatch, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @request, col: :stringmatch %>
  </div>

  <div class="form-field">
    <%= f.submit "Edit Request", class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/requests/index.html.erb
<h1>Views#index</h1>
<p>Find me in app/views/views/index.html.erb</p>

app/views/requests/new.html.erb
<h1>New Request</h1>

<div class="sign-up">

  <%= form_for @request do |f| %>
  <div class="form-field">
    <%= f.label :website%>
    <%= f.text_field :website, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @request, col: :website %>
  </div>

  <div class='form-field'>
    <%= f.label :stringmatch %>
    <%= f.text_field :stringmatch, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @request, col: :stringmatch %>
  </div>

  <div class="form-field">
    <%= f.submit "Create Request", class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/requests/show.html.erb
<h1>Views#show</h1>
<p>Find me in app/views/views/show.html.erb</p>

app/views/requests/update.html.erb
<h1>Views#update</h1>
<p>Find me in app/views/views/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if obj.errors[col].any? %>
<div class="error-message"><strong><%= (col.to_s + "_").capitalize.gsub!(/\_/, " ") %></strong> <%= obj.errors[col].first %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<div class="sign-up">

  <%= form_for @user do |f| %>
  <div class="form-field">
    <%= f.label :name%>
    <%= f.text_field :name, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :name %>
  </div>

  <div class='form-field'>
    <%= f.label :email%>
    <%= f.text_field :email, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :email %>
  </div>

  <div class="form-field">
    <%= f.submit "Edit Profile", class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>New User</h1>

<div class="sign-up">

  <%= form_for @user do |f| %>
  <div class="form-field">
    <%= f.label :name%>
    <%= f.text_field :name, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :name %>
  </div>

  <div class='form-field'>
    <%= f.label :email%>
    <%= f.text_field :email, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :email %>
  </div>

  <div class="form-field">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :username %>
  </div>

  <div class="form-field">
    <%= f.label :password%>
    <%= f.password_field :password, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :password %>
  </div>

  <div class="form-field">
    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation, class: 'form-control'%>
    <%= render "shared/error_messages", obj: @user, col: :password_confirmation %>
  </div>

  <div class="form-field">
    <%= f.submit "Sign Up", class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>User Profile</h2>
<div>
  <strong>Name: </strong><%= @user.name %>
</div>
<div>
  <strong>Username: </strong><%= @user.username %>
</div>
<div>
  <strong>Email: </strong><%= @user.email %>
</div>

<div class="button-display">
  <%= link_to "Edit Profile", edit_user_path(@user.id), class:"btn btn-primary active", role:"button" %>
  <%= link_to "Create Request", new_request_path, class:"btn btn-primary active", role:"button" %>
</div>


<% if !@user.requests.empty? %>
  <h3>Requests: </h3>
  <% @user.requests.each do |request| %>
    <div>
      <strong>Website: </strong><%= request.website %>
    </div>
    <div>
      <strong>Match: </strong><%= request.stringmatch %>
    </div>
    <div class="button-display">
      <%= link_to "Edit", edit_request_path(request.id), class:"btn btn-primary active", role:"button" %>
      <%= button_to "Delete", request_path(request.id), method: :delete, class:"btn btn-danger" %>
    </div>
  <% end %>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>